version: 2

workflows:
  version: 2
  build:
    jobs:
      - build
      - build-android:
          requires:
            - build

jobs:
  build:
    docker:
      - image: circleci/golang:1.12
      - image: redis

    steps:
      - checkout

      - run:
          name: Install emmy
          command: go install

      - run:
          name: Run unit tests
          command: make test

      - run:
          name: Run integration tests
          command: make test-integration

  build-android:
    docker:
      - image: circleci/golang:1.12

    working_directory: /go/src/github.com/emmyzkp/emmy

    steps:
      - checkout

      - run:
          name: Install Android SDK & NDK
          command: |
           sudo apt-get install libc6-dev-i386 lib32z1 default-jdk
           wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
           unzip sdk-tools-linux-4333796.zip -d android-sdk
           yes | android-sdk/tools/bin/sdkmanager --licenses
           android-sdk/tools/bin/sdkmanager ndk-bundle

      - run:
          name: Install gomobile tool
          command: go get golang.org/x/mobile/cmd/gomobile

      - run:
          name: Create emmy android archive
          command: |
           gomobile init
           GO111MODULE=on go install -i
           ANDROID_HOME=android-sdk make android

      - store_artifacts:
          path: emmy.aar

