version: 2

workflows:
  version: 2
  build:
    jobs:
      - build
      - build-android:
          requires:
            - build

jobs:
  build:
    docker:
      - image: circleci/golang:1.12
      - image: redis

    steps:
      - checkout

      - run:
          name: Install emmy
          command: go install

      - run:
          name: Run unit tests
          command: make test

      - run:
          name: Run integration tests
          command: make test-integration

  build-android:
    docker:
      - image: circleci/golang:1.12

    working_directory: /go/src/github.com/emmyzkp/emmy

    steps:
      - checkout

      - run:
          name: Create emmy android archive
          command: make android

      - store_artifacts:
          path: emmy.aar

