version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
      - image: redis

    working_directory: /go/src/github.com/emmyzkp/emmy

    steps:
      - checkout

      - run:
          name: Install emmy
          command: go install

      - run:
          name: Run unit tests
          command: make test

      - run:
          name: Run integration tests
          command: make test-integration

